### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by QieSima** [ivalab/AffKpNet#3]
When I try to run the evaluate code with command 
`CUDA_VISIBLE_DEVICES=0 python eval_aff_mask.py --dataset umd_self_kp --model danet_kp --resume-dir /danet_kp/umd_gt/model --base-size 480 --crop-size 480 --workers 1 --backbone resnet101 --multi-grid --multi-dilation 4 8 16 --eval`
I got the error as below
```
Traceback (most recent call last):
  File "eval_aff_mask.py", line 19, in <module>
    import encoding.utils as utils
  File "/root/anaconda3/lib/python3.8/site-packages/torch_encoding-1.2.2b20220804-py3.8.egg/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/root/anaconda3/lib/python3.8/site-packages/torch_encoding-1.2.2b20220804-py3.8.egg/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/root/anaconda3/lib/python3.8/site-packages/torch_encoding-1.2.2b20220804-py3.8.egg/encoding/nn/encoding.py", line 19, in <module>
    from ..functions import scaledL2, aggregate, pairwise_cosine
  File "/root/anaconda3/lib/python3.8/site-packages/torch_encoding-1.2.2b20220804-py3.8.egg/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/root/anaconda3/lib/python3.8/site-packages/torch_encoding-1.2.2b20220804-py3.8.egg/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/root/anaconda3/lib/python3.8/site-packages/torch_encoding-1.2.2b20220804-py3.8.egg/encoding/lib/__init__.py", line 9, in <module>
    cpu = load('enclib_cpu', [
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1506, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1562, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
```
Could you help me find out where is the problem?

**Comment by lily983** [comment]
I experienced the same problem. I changed the 'sys.path.append' to the directory of AffKpNet on my computer. But the error still exists. Could you make the instruction more detailed, please? Thanks.
